#!/bin/bash
#
# Robin Moser, 2018
#
# Depricated!

tmplog="/home/moser/log/mail.temp.log"
interface="org.freedesktop.Notifications"

dbus-monitor "interface='$interface'" |
  while read -r line; do
    msg=$(echo $line | grep "string \"" | sed -e 's/string \"\(.*\)\"/\1/g')
    if [ -n "$msg" ] && [[ $msg == *"Sie haben"* ]]; then
      log=$(date +"[%m-%d %H:%M:%S]")" $msg"
      echo "$log" >> $tmplog
    fi
  done
